### ISSUE TITLE
Add support for service.xml (like symfony-standard does)

### ISSUE THREAD

**Issue by giginos** [bcremer/shopware-plugin-schemas#3]
Actually the new plugin-system does support config.xml and menu.xml (and serves dtds). Will SW 5.2 also support the service.xml as it was announced on the scd? This would be awesome :-)

**Comment by bcremer** [comment]
It already does load the `services.xml`. See commit: https://github.com/shopware/shopware/commit/016eae2412680ff55da78fae858f990606c865fb

The directory structure is the following:

```
SwagPromotion
├── Resources
│   ├── snippets
│   ├── views
│   ├── menu.xml
│   ├── config.xml
│   └── services.xml
├── Services
├── Controllers
├── Models
├── plugin.xml
├── phpunit.xml.dist
└── SwagPromotion.php
```
